### ISSUE TITLE
Doesn't build with zig 0.6.0

### ISSUE THREAD

**Issue by pjz** [zigtools/zpm#5]
..and I can't find anything saying what version it _should_ build against.  Or is it now considered totally obsolete?

The first few lines of the results of 'zig build' on ubuntu 20.04 are:
```
$ zig build                                                                                                                                                                                         
Semantic Analysis [1042/1665] ./src/main.zig:594:8: error: no member named 'cwd_dir' in struct 'std.child_process.ChildProcess'                                                                                      
    git.cwd_dir = target_dir;                                                                                                                                                                                        
       ^                                                                                                                                                                                                             
./src/main.zig:556:13: note: referenced here                                                                                                                                                                         
            try runGit(&[_][]const u8{                                                                                                                                                                               
            ^                                                                                                                                                                                                        
./src/main.zig:509:76: note: referenced here                                                                                                                                                                         
    installPackageInternal(allocator, target_dir, full_name, install_mode) catch |err| switch (err) {                                                                                                                
                                                                           ^                                                                                                                                         
./src/main.zig:237:43: note: referenced here                                                                                                                                                                         
                    success = success and try installPackage(allocator, target_dir, repo_spec, cli.options.mode);                                                                                                    
                                          ^                                                                                                                                                                          
zpm...The following command exited with error code 1:                                                                
...
```

**Comment by alexnask** [comment]
Hi, I agree this should be mentioned in the README.  
I assume this requires zig master (or some reasonably recent zig), as do most zig projects.

**Comment by ikskuh** [comment]
Right now, zpm itself is unmaintained until i find the time for a rewrite. I'll hook it up against CI then so it will keep up with latest master

**Comment by Epikest** [comment]
this issue should be closed, we're up to 0.10+ now
